sudo: false
language: node_js
node_js:
- 6
before_script:
- npm install -g grunt-cli
script: grunt ci
env:
  global:
    - SAUCE_USERNAME=devpaul
    - secure: xtD6L/1Bf2oAVKMB7J7vTpozNV+7rndSlj5tviV7MZ5+sWcQIeBsbyCkUaY7PZam+IFig88JTVtwcARLt05N+E4PbtnXsJRNXmbk8E0T8MY30IZXp1OdF28JMJbcO/mEKyDnGnFtnY2faDmx76Ql+EKnzbCdRdv9sVbk+yy9oq/ILxV9SJPe2b7LTFwXBscGmWjpsh+jWqwm3NsMCcicvZidURfya5RUMuG/Tq6qO3S2J2OYsA9Zqq8jJ4TiBK3ooikkkMc/AnuBDqq2mejpvd/+g4QLa5otNqMZk3o5bpASnsX3UxzoikBaxRc5jdTJVp00mdTLdXxXUfkNP5VgKPuU7uZK9NRMi7goIdrFtKj5CB7zpo9a+OgyYYprnQdAzxgYfcX5kgMlph9Lt+Xl4nmIl2EJ71pN9w4lokT0cldeUsrfsJVs/WsfjnpxU7TV/Kk1ZfV3Qqu3DiKXHjENIj0JVzs5XUMeUz0E7TRbTEXy540C+MLYZwdaBpK25wviVSQnLjqoEz8IUzRVs1qKQL7RMfkiqCWKipNPnXfMaQAR7CZjCk5SpPqtfbrfRpRxD7BzOrXb3zYS4uJ2LVVCtpsBNQ8WBTbgn8+sMICqFdbIoxsjfFmTUrcHf/M37R0SYxKShFqRwCySJ6btJp1MwdnoVMCw2gxgqM/LwIIkqbg=
